### procesar todos los datos
GET http://localhost:3000/api/productos

### procesar productos por id
GET http://localhost:3000/api/productos/2

### crear producto
POST http://localhost:3000/api/productos
Content-Type: application/json

{
  "nombre": "Iphone 16",
  "precio": 12000,
  "categoria": "telefonia",
  "stock": 10
}

### Actualizar producto
PUT http://localhost:3000/api/productos/2
Content-Type: application/json

{
  "nombre": "Teclado inalambrico",
  "precio": 2500,
  "categoria": "perifericos",
  "stock": 50
}

### Borrar producto
DELETE http://localhost:3000/api/productos/6